.TH SHOTCUT "1" "September 2023" "Shotcut" "User Commands"
.SH NAME
shotcut \- video editor
.SH SYNOPSIS
.B shotcut
[\fI\,options\/\fR] \fI\,[FILE]...\/\fR
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Displays this help.
.TP
\fB\-v\fR, \fB\-\-version\fR
Displays version information.
.TP
\fB\-\-fullscreen\fR
Fill the screen with the Shotcut window.
.TP
\fB\-\-noupgrade\fR
Hide upgrade prompt and menu item.
.TP
\fB\-\-glaxnimate\fR
Run Glaxnimate instead of Shotcut.
.TP
\fB\-\-gpu\fR
Use GPU processing.
.TP
\fB\-\-clear\-recent\fR
Clear Recent on Exit
.TP
\fB\-\-appdata\fR <directory>
The directory for app configuration and data.
.TP
\fB\-\-QT_SCALE_FACTOR\fR <number>
The scale factor for a high-DPI screen
.TP
\fB\-\-QT_SCREEN_SCALE_FACTORS\fR <list>
A semicolon-separated list of scale factors for each screen
.TP
\fB\-\-QT_SCALE_FACTOR_ROUNDING_POLICY\fR <string>
How to handle a fractional display scale: Round, Ceil, Floor, RoundPreferFloor, PassThrough
.TP
\fB\-\-SDL_AUDIODRIVER\fR <string>
Which operating system audio API to use: alsa, arts, dsp, esd, jack, pipewire, pulseaudio
.SS "Arguments:"
.TP
[FILE]...
Zero or more files or folders to open
.SH "INTERNET"
Best to start at https://shotcut.org/tutorials/
