name: shotcut
version: '18.01'
summary: Free, cross-platform, open source video editor
description: >
  Shotcut is a free, open source, cross-platform video editor for Windows,
  Mac and Linux. Major features include support for a wide range of formats;
  no import required meaning native timeline editing; Blackmagic Design
  support for input and preview monitoring; and resolution support to 4k.

grade: stable
confinement: classic

apps:
  shotcut:
    command: bin/desktop-launch $SNAP/Shotcut.app/shotcut
  ffmpeg:
    command: $SNAP/Shotcut.app/ffmpeg
  ffplay:
    command: $SNAP/Shotcut.app/ffplay
  ffprobe:
    command: $SNAP/Shotcut.app/ffprobe
  melt:
    command: $SNAP/Shotcut.app/melt
  qmelt:
    command: $SNAP/Shotcut.app/qmelt

parts:
  shotcut:
    after: [desktop-qt5]
    plugin: dump
    source: 'https://github.com/mltframework/shotcut/releases/download/v18.01/shotcut-linux-x86_64-180102.tar.bz2'
    organize:
      'Shotcut': './'

