name: build-shotcut-windows

on:
  workflow_dispatch:
  schedule:
    # nightly
    - cron: '0 8 * * *'

jobs:
  build:
    if: ${{ github.repository_owner == 'mltframework' }}
    runs-on: windows-latest
    env:
      SM_API_KEY: ${{ secrets.SM_API_KEY }}
      SM_CLIENT_CERT_FILE: ${{ github.workspace }}/Certificate_pkcs12.p12
      SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
      SM_HOST: ${{ vars.SM_HOST }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            autotools base-devel bzip2 coreutils git gzip tar xz zip
            perl-List-MoreUtils perl-XML-Parser
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-yasm
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-eigen3
            mingw-w64-x86_64-dlfcn
            mingw-w64-x86_64-fftw
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-gettext-tools
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-lame
            mingw-w64-x86_64-libarchive
            mingw-w64-x86_64-libepoxy
            mingw-w64-x86_64-libexif
            mingw-w64-x86_64-libimagequant
            mingw-w64-x86_64-libsamplerate
            mingw-w64-x86_64-libtheora
            mingw-w64-x86_64-libvorbis
            mingw-w64-x86_64-libvpx
            mingw-w64-x86_64-libwebp
            mingw-w64-x86_64-libxml2
            mingw-w64-x86_64-onevpl
            mingw-w64-x86_64-openblas
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-opus
            mingw-w64-x86_64-potrace
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-rubberband
            mingw-w64-x86_64-sox
            mingw-w64-x86_64-svt-av1
            mingw-w64-x86_64-vid.stab
            mingw-w64-x86_64-vulkan-headers
            mingw-w64-x86_64-vulkan-loader
            mingw-w64-x86_64-x264
            mingw-w64-x86_64-x265
            mingw-w64-x86_64-zimg

      - name: Set version
        shell: msys2 {0}
        run: echo "VERSION=$(date +"%y.%-m.%-d")" >> "$GITHUB_ENV"

      - name: Install dependencies
        shell: msys2 {0}
        run: |
          pacman --noconfirm -Rdd mingw-w64-x86_64-aom
          echo VERSION=$VERSION
          cd "$HOME"
          mkdir Qt
          cd Qt
          echo Downloading Qt
          curl -kLO --no-progress-meter https://s3.amazonaws.com/misc.meltymedia/shotcut-build/qt-6.8.3-x64-mingw.txz
          echo Extracting Qt
          tar -xJf qt-6.8.3-x64-mingw.txz
          rm qt-6.8.3-x64-mingw.txz
          cd ..
          echo Downloading a few prebuilt dependencies
          curl -kLO --no-progress-meter https://s3.amazonaws.com/misc.meltymedia/shotcut-build/mlt-prebuilt-mingw64-v6.txz
          echo Extracting prebuilt dependencies
          tar -xJf mlt-prebuilt-mingw64-v6.txz
          rm mlt-prebuilt-mingw64-v6.txz

      - name: Build
        shell: msys2 {0}
        run: |
          echo INSTALL_DIR=\"$(pwd)/build\"
          echo INSTALL_DIR=\"$(pwd)/build\" > build-shotcut.conf
          echo SHOTCUT_VERSION=\"$VERSION\" >> build-shotcut.conf
          echo SHOTCUT_HEAD=0 >> build-shotcut.conf
          echo SHOTCUT_REVISION=origin/${{ github.head_ref || github.ref_name }} >> build-shotcut.conf
          bash scripts/build-shotcut-msys2.sh

      - name: Setup SM_CLIENT_CERT_FILE
        if: ${{ github.repository_owner == 'mltframework' }}
        shell: bash
        run: |
          printf "%s" "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > "$SM_CLIENT_CERT_FILE"

      - name: Setup Software Trust Manager
        if: ${{ github.repository_owner == 'mltframework' }}
        uses: digicert/code-signing-software-trust-action@v1
        with:
          simple-signing-mode: true

      - name: Sign all the executables
        if: ${{ github.repository_owner == 'mltframework' }}
        shell: bash
        run: |
          smctl healthcheck
          #smctl keypair list
          for EXE in build/Shotcut/*.exe; do
            echo Signing ${EXE}
            smctl sign --simple --keypair-alias key_1464644718 --input ${EXE}
          done

      - name: Package the portable zip
        shell: msys2 {0}
        run: |
          cd build
          zip -gr shotcut-win64-$VERSION.zip Shotcut

      - name: Upload portable artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-x64-portable
          path: ./build/shotcut-win64-*.zip

      - name: Package the installer
        shell: msys2 {0}
        run: |
          PATH="$HOME/bin:$PATH"
          pushd "$HOME/bin"
          curl -kLO --no-progress-meter https://s3.amazonaws.com/misc.meltymedia/shotcut-build/iscc632.txz
          tar -xJf iscc632.txz
          popd
          cd build
          echo Extracting installer dependencies
          curl -kLO --no-progress-meter https://s3.amazonaws.com/misc.meltymedia/shotcut-build/innosetup-opera-1.txz
          tar -xJf innosetup-opera-1.txz
          rm innosetup-opera-1.txz
          echo Running Inno Setup Compiler
          ISCC -Q -O. shotcut.iss

      - name: Sign the installer
        if: ${{ github.repository_owner == 'mltframework' }}
        shell: bash
        run: |
          cd build
          smctl sign --simple --keypair-alias key_1464644718 --input shotcut-setup.exe
          mv shotcut-setup.exe shotcut-win64-$VERSION.exe

      - name: Upload installer artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-x64-installer
          path: ./build/shotcut-*.exe

      - name: Upload packages to S3
        if: ${{ github.repository_owner == 'mltframework' && github.ref_name == 'master' }}
        shell: msys2 {0}
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}
          export AWS_DEFAULT_REGION=us-east-1
          for file in build/*.{exe,zip}; do
            echo Uploading "$file" to S3
            aws s3 cp "$file" s3://builds.us.meltytech/shotcut/ --no-progress
          done
